/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import java.awt.Graphics;
import java.awt.Image;
import java.security.Principal;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author Valentin Barros
 */
public class Menu extends javax.swing.JFrame {

    private EscritorioPersonalizado escritorio;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        escritorio = new EscritorioPersonalizado();
        this.setContentPane(escritorio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPMenuPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInscripcionA = new javax.swing.JMenu();
        jMIAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMICargaMateria = new javax.swing.JMenuItem();
        jMInscripcion = new javax.swing.JMenu();
        jMIInscripcion = new javax.swing.JMenuItem();
        jMIMateriaXAlumno = new javax.swing.JMenuItem();
        jMIAlumnoXMateria = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jDPMenuPrincipal.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDPMenuPrincipalLayout = new javax.swing.GroupLayout(jDPMenuPrincipal);
        jDPMenuPrincipal.setLayout(jDPMenuPrincipalLayout);
        jDPMenuPrincipalLayout.setHorizontalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jDPMenuPrincipalLayout.setVerticalGroup(
            jDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(850, 34));

        jMInscripcionA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AlumnoX32.png"))); // NOI18N
        jMInscripcionA.setText("Alumno");

        jMIAlumno.setText("Inscripcion de Alumnos");
        jMIAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumnoActionPerformed(evt);
            }
        });
        jMInscripcionA.add(jMIAlumno);

        jMenuBar1.add(jMInscripcionA);

        jMMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MateriasChica.png"))); // NOI18N
        jMMateria.setText("Materia");

        jMICargaMateria.setText("Inscripcion de materia");
        jMICargaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICargaMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMICargaMateria);

        jMenuBar1.add(jMMateria);

        jMInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inscripcion.png"))); // NOI18N
        jMInscripcion.setText("Inscripcion");

        jMIInscripcion.setText("Inscripcion a Materia");
        jMIInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInscripcionActionPerformed(evt);
            }
        });
        jMInscripcion.add(jMIInscripcion);

        jMIMateriaXAlumno.setText("Materias cursadas por alumno");
        jMIMateriaXAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMateriaXAlumnoActionPerformed(evt);
            }
        });
        jMInscripcion.add(jMIMateriaXAlumno);

        jMIAlumnoXMateria.setText("Alumos que cursan una materia");
        jMIAlumnoXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumnoXMateriaActionPerformed(evt);
            }
        });
        jMInscripcion.add(jMIAlumnoXMateria);

        jMenuBar1.add(jMInscripcion);

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_16560328.png"))); // NOI18N
        jMSalir.setText("Salir");

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMISalir);

        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMIAlumnoActionPerformed

    private void jMICargaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICargaMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargarMateria form = new CargarMateria();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMICargaMateriaActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        // TODO add your handling code here:
           dispose();
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMIInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInscripcionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InscripcionMateria form = new InscripcionMateria();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIInscripcionActionPerformed

    private void jMIMateriaXAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMateriaXAlumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AlumnoMateria form = new AlumnoMateria();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIMateriaXAlumnoActionPerformed

    private void jMIAlumnoXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumnoXMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MateriaAlumno form = new MateriaAlumno();
        form.setVisible(true);
        escritorio.add(form);
        escritorio.moveToFront(form);
    }//GEN-LAST:event_jMIAlumnoXMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMenuPrincipal;
    private javax.swing.JMenuItem jMIAlumno;
    private javax.swing.JMenuItem jMIAlumnoXMateria;
    private javax.swing.JMenuItem jMICargaMateria;
    private javax.swing.JMenuItem jMIInscripcion;
    private javax.swing.JMenuItem jMIMateriaXAlumno;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMInscripcion;
    private javax.swing.JMenu jMInscripcionA;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

 public class FondoDesktopPane extends JDesktopPane {
    private Image imagenFondo;

    public FondoDesktopPane(String rutaImagen) {
        imagenFondo = new ImageIcon(rutaImagen).getImage();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(imagenFondo, 0, 0, getWidth(), getHeight(), this);
    }
}

}
